<template>
   <div class = "info-box">

      <h1> My Education</h1>
      <p> College : Vishwakarma Institute of Technology , Pune</p>
      <p> Program : Bachelors of Technology</p>
      <p> Course : Information Technology</p>
      
   </div>

</template>
<style>
   body{
      background-color:#f0f0f0;
      font-family:Arial, sans-serif;
   }
   .info-box{
      border: 2px solid #0077b6;
      border-radius:10px;
      padding:20px;
      width:500px;
      margin:0 auto;
   
}
   h1{
      color:#0077b6
   }
</style>